export const TEXT = {
  LOGIN: "Login",
  SIGNUP: "Sign Up",
  LOGIN_TITLE: "Welcome Back",
  LOGIN_SUBTITLE: "Login to continue",
  SIGNUP_TITLE: "Create Account",
  SIGNUP_SUBTITLE: "Join us and start your journey!",
  SEND_OTP: "Send OTP",
  VERIFY_OTP: "Verify OTP",
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ALREADY_HAVE_ACCOUNT: "Already have an account?",
  FORGOT_PASSWORD: "Forgot password?",
  RESET_PASSWORD: "Reset Password",
  RESET_PASSWORD_TITLE: "Reset Your Password",
  RESET_PASSWORD_SUBTITLE: "Follow the steps to reset your password",
  CONTINUE: "Continue",
  VERIFY_EMAIL_TITLE: "Verify Your Email",
  VERIFY_EMAIL: "Verify Email",
  VERIFY_EMAIL_SUBTITLE: "Enter the 6-digit code sent to your email address.",
};